name: Build Android APK

on:
  workflow_dispatch: # 允许手动触发
  push:
    tags:
      - 'v*'         # 只有打标签 v开头 时触发发布流程

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # 缓存 Bun
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 缓存 Gradle (加速构建)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Prebuild
        run: npx expo prebuild --platform android

      - name: Decode Keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d -i > ./android/app/my-upload-key.keystore

      - name: Build APK
        working-directory: ./android
        env:
          # 环境变量
          EXPO_PUBLIC_DANDANPLAY_API_URL: ${{ secrets.EXPO_PUBLIC_DANDANPLAY_API_URL }}
          
          ORG_GRADLE_PROJECT_MYAPP_UPLOAD_STORE_FILE: my-upload-key.keystore
          ORG_GRADLE_PROJECT_MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ORG_GRADLE_PROJECT_MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache

      - name: Rename APK
        id: rename_apk
        run: |
          VERSION=$(grep '"version":' package.json | cut -d '"' -f 4)
          NEW_NAME="nekofin-${VERSION}-arm64-v8a.apk"
          mv android/app/build/outputs/apk/release/app-release.apk $NEW_NAME
          echo "apk_path=$NEW_NAME" >> $GITHUB_OUTPUT

      # -------------------------------------------------------
      # 场景 1: 手动触发或普通提交 -> 上传 Artifact (下载是 .zip)
      # -------------------------------------------------------
      - name: Upload Artifact (For Manual Build)
        uses: actions/upload-artifact@v4
        # 如果不是打标签，就执行这一步
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: nekofin-build-artifact
          path: ${{ steps.rename_apk.outputs.apk_path }}
          retention-days: 3

      # -------------------------------------------------------
      # 场景 2: 打标签推送 (git push --tags) -> 发布 Release (下载是 .apk)
      # -------------------------------------------------------
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        # 只有是打标签时，才执行这一步
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.rename_apk.outputs.apk_path }}
          generate_release_notes: true
          draft: false
          prerelease: false